### PR TITLE
Tejas

### PR DESCRIPTION
**Pull request by Tejas-Khot**
- organized the files into a modular structure
- added nnet module with convolution net layer implementation
- cleaned up code and made the code style uniform

### CODE REVIEW

**Comment by duguyue100** [comment]
Basically this is what I find in the changes:

+ I saw that you add `.project` and `.pydevproject` to `.gitignore`, but it's still in this pull request as new files. Seems like I can't delete them, if someone can please do it.

+ all codes are wrapped in two folders: `cifar-test` and `destin`, it now looks like a package. I think it's a good thing, I suggest all of us use this version. 

+ the rests are some doc strings for the previous codes, it's fine from my view.

+ convnet layer is added in to a folder. right now the code is fine, some tests needed.

The above is my comments, I hope others can contribute your idea before I merge

**Comment by jswiergo** [comment]
Hi, I am updating myself with the current state of Destin project. My comments after reviewing this PR.
* the code is better organized now, the new comments are heplfull, well done!
* in the ConvLayer there is a reference to general_destin, though I have not found it (?)
* the ConvLayer seems to be standalone piece of code now. @Tejas-Khot, is it your plan to integrate this new algorithm with Destin code, introduce new algorithm choice to Destin Network class, create test cases?

I think it would be good to merge this refactoring/comments part of changes into main repo now, looks like very good work. All code under the nnet directory I suggest to keep in a separate branch till more integration is done.

**Comment by Tejas-Khot** [comment]
Thank you @jswiergo  

The plan is to upgrade the python-destin module to using theano(and hence GPU computing) which would involve a complete re-design of the architecture. The ConvLayer is a standalone module and is the first step towards implementation of Convolutional DeSTIN. In time, other parts of python-destin will also be upgraded to use these. Our plan is to have as much modularity as possible so it increases ease of usage and re-use. 

Thank you for pointing out the general_destin error. I had forgotten to change it. Its corrected now. It was my temporary alias for module name.

**Comment by jswiergo** [comment]
Thanks for info!

I have one remark regarding coding style. I see you've improved the code, though I found you've introduced tab indentations to the new files. I would suggest to keep everything consistent.
The OpenCog standard uses 4 spaces. I have found wiki page: http://wiki.opencog.org/w/Development_standards, though there is not much related to Python.

I am not attached to any special standard but I think it is important to stick to one of them. Let us consider this for example:
https://www.python.org/dev/peps/pep-0008/
https://google-styleguide.googlecode.com/svn/trunk/pyguide.html

Could you OpenCoggers confirm the recommended Python coding style and update the wiki page?

**Comment by Tejas-Khot** [comment]
@jswiergo I have used tab=4 spaces for my code
For viewing, GitHub defaults to tab=8 spaces and hence it looks odd. A way to resolve it is given here:
http://stackoverflow.com/questions/8833953/how-to-change-tab-size-on-github

You can append ?ts=2 or ?ts=4 to the URL to change the tab-size.
Example: https://github.com/Tejas-Khot/python-destin/blob/tejas/destin/nnet/conv.py?ts=4
It seems that the value can be anything from 1 to 12. It does not work on Gists or raw file views though.

**Comment by jswiergo** [comment]
Yes, sure, I can change the settings on my side, that is not problem for me. But when the code is public I would rather think about all other folks in the unknown future who will clone the repo from github locally and use their private editor to read and change the code.
Should every of this guys adjust their settings? Hope not, so that is is why I recommended some common standards, coding style, naming conventions etc. It is a common practice, useful for everyone.

**Comment by duguyue100** [comment]
@jswiergo I don't believe fixing URL is the solution. I just clone his branch to my Mac, and I found the same 8-spaced code that displayed in the file of `conv.py`. I believe there is something wrong with the editor.

Regarding to Python coding style. yeah i think we should adapt to one of above mentioned. The style you saw in this changes actually largely from Eclipse's PyDev, so you have something like `@param` thingy. I think we should adapt the project [Blocks](https://github.com/mila-udem/blocks) coding style, helpful when you generating the entire documentation.

**Comment by jswiergo** [comment]
>@jswiergo I don't believe fixing URL is the solution. 
Just to replace all tabs to 4 spaces and avoid tabs in the source will suffice.

> I think we should adapt the project Blocks coding style, helpful when you generating the entire documentation
Perfect! They are following PEP 8 guidelines.

**Pull request merged**
